### ISSUE TITLE
integration stopped after round one hour

### ISSUE THREAD

**Issue by dl6dbh** [jannickfahlbusch/ha-ppc-smgw#24]
![grafik](https://github.com/user-attachments/assets/88479b54-4311-4114-83db-dbb7b0483c20)
![grafik](https://github.com/user-attachments/assets/7d9fdde4-4cbd-49c9-8de0-0ecce7e111d5)

**Comment by jannickfahlbusch** [comment]
Thank you for the report. I've just merged #25 which should fix this issue.
